命令稿啟動於 2017年03月12日 (週日) 13時01分27秒
]0;ubuntu@ubuntu-BM1AF-BP1AF-BM6AF: ~/lab1ubuntu@ubuntu-BM1AF-BP1AF-BM6AF:~/lab1$ ./hw1g++ -o hw1 hw1.cppexit[K./uva11538[6Pexitg++ -o hw1 hw1.cpp
]0;ubuntu@ubuntu-BM1AF-BP1AF-BM6AF: ~/lab1ubuntu@ubuntu-BM1AF-BP1AF-BM6AF:~/lab1$ g++ -o hw1 hw1.cpp./hw1[Kg++ -o hw1 hw1.cpp./hw1[K
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1
]0;ubuntu@ubuntu-BM1AF-BP1AF-BM6AF: ~/lab1ubuntu@ubuntu-BM1AF-BP1AF-BM6AF:~/lab1$ exit

命令稿已於 2017年03月12日 (週日) 13時01分34秒
 完成